export const defaultPlanId = "free"

export const pricingPlans = [
  {
    id: "free",
    name: "Free",
    description: "Perfect for individuals getting started with basic access.",
    price: "$0",
    priceIntervalName: "per month",
    stripe_price_id: null,
    stripe_product_id: null,
    note: null,
    features: [
      "Live Feed access",
      "Fleet Manager (up to 5 vehicles)",
      "Insights Snapshot",
      "3 Route Alerts",
      "5 Geofences",
      "1 user seat",
      "Community support",
    ],
    targetUser: "Individual/Basic",
  },
  {
    id: "starter",
    name: "Starter",
    description: "Ideal for small operators needing more capacity and exports.",
    price: "$9",
    priceIntervalName: "per month",
    stripe_price_id: "price_starter_monthly",
    stripe_product_id: "prod_starter",
    note: null,
    features: [
      "Everything in Free",
      "Trip Planner",
      "25 Route Alerts",
      "50 Geofences",
      "Data Export",
      "5 user seats",
      "Email support (48h response)",
    ],
    targetUser: "Individual/Small Op",
  },
  {
    id: "pro",
    name: "Pro",
    description: "Unlimited everything for professionals demanding full control.",
    price: "$29",
    priceIntervalName: "per month",
    stripe_price_id: "price_pro_monthly",
    stripe_product_id: "prod_pro",
    note: null,
    features: [
      "Everything in Starter",
      "Telemetry Sync",
      "Unlimited Route Alerts",
      "Unlimited Geofences",
      "Custom Reports",
      "API Access",
      "Unlimited user seats",
      "Priority support (24h SLA)",
    ],
    targetUser: "Pro/Power User",
  },
  {
    id: "business",
    name: "Business",
    description: "Scalable for teams — volume discounts from 10+ seats.",
    price: "$49",
    priceIntervalName: "per user / month",
    stripe_price_id: "price_business_monthly",
    stripe_product_id: "prod_business",
    note: "$39/user at 10+  ·  $29/user at 50+",
    features: [
      "Everything in Pro",
      "Custom Integrations",
      "Team collaboration tools",
      "Volume-based pricing",
      "Dedicated account manager",
      "99.9% uptime SLA",
    ],
    targetUser: "Business/Team",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    description: "Custom contracts for large organisations with premium SLAs.",
    price: "Custom",
    priceIntervalName: "billed annually",
    stripe_price_id: null,
    stripe_product_id: null,
    note: "Contact sales@matatupulse.com for a demo & quote",
    features: [
      "Everything in Business",
      "On-premise deployment",
      "SOC2 Compliance",
      "24/7 premium support",
      "Custom SLAs & training",
      "Unlimited everything",
    ],
    targetUser: "Enterprise",
  },
]