<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 retro_anime_vintage_volkswagen_van.glb --transform
Author: Jungle Jim (https://sketchfab.com/jungle_jim)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-anime-vintage-volkswagen-van-5772dc675e5347e09979998bfcf54938
Title: Retro Anime Vintage Volkswagen Van
-->

<script>
  import { T } from "@threlte/core"
  import { useGltf } from "@threlte/extras"

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf("./retro_anime_vintage_volkswagen_van-transformed.glb")
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Object_4.geometry}
      material={gltf.materials.material_0}
      rotation={[Math.PI / 2, 0, 0]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
