// src/lib/features/auth/permissions.ts
export const ACTIONS = {
  VEHICLE_LIST: "vehicle:list",
  VEHICLE_VIEW: "vehicle:view",
  VEHICLE_ADD: "vehicle:add",
  VEHICLE_EDIT: "vehicle:edit",
  VEHICLE_GROUP_LIST: "vehicle_group:list",
  VEHICLE_GROUP_ADD: "vehicle_group:add",
  VEHICLE_GROUP_DEL: "vehicle_group:del",
  DRIVER_LIST: "driver:list",
  DRIVER_ADD: "driver:add",
  DRIVER_EDIT: "driver:edit",
  BOOKING_LIST: "booking:list",
  BOOKING_ADD: "booking:add",
  BOOKING_EDIT: "booking:edit",
  TRACKING_LIVE: "tracking:live",
  TRACKING_HISTORY: "tracking:history",
  GEOFENCE_LIST: "geofence:list",
  GEOFENCE_ADD: "geofence:add",
  GEOFENCE_EDIT: "geofence:edit",
  GEOFENCE_DEL: "geofence:del",
  GEOFENCE_EVENTS: "geofence:events",
  FUEL_LIST: "fuel:list",
  FUEL_ADD: "fuel:add",
  FUEL_EDIT: "fuel:edit",
  FINANCE_LIST: "finance:list",
  FINANCE_ADD: "finance:add",
  FINANCE_EDIT: "finance:edit",
  REPORTS_VIEW: "reports:view",
  SETTINGS_ALL: "settings:all",
  REMINDER_LIST: "reminder:list",
  CUSTOMER_LIST: "customer:list",
  CUSTOMER_VIEW: "customer:view",
  CUSTOMER_ADD: "customer:add",
  CUSTOMER_EDIT: "customer:edit",
} as const

export type Action = (typeof ACTIONS)[keyof typeof ACTIONS]
export const ALL_ACTIONS = Object.values(ACTIONS)