// src/lib/auth/permissions.js
// Updated version — includes ORG_CHAIR and OWNER

import { ROLES } from './roles';
import { ACTIONS } from './permissions';  // adjust path as needed

export const ROLE_PERMISSIONS = {
  // ────────────────────────────────────────────────
  // Full / God-mode roles (highest privilege)
  // ────────────────────────────────────────────────
  [ROLES.ADMIN]:                Object.values(ACTIONS),
  [ROLES.SUPER_ADMIN]:          Object.values(ACTIONS),
  [ROLES.COMPANY_OWNER]:        Object.values(ACTIONS),
  [ROLES.ORG_CHAIR]:            Object.values(ACTIONS),     // added – organizational chair / board-level owner
  [ROLES.OWNER]:                Object.values(ACTIONS),     // added – generic top-level owner

  // ────────────────────────────────────────────────
  // Management & Operations
  // ────────────────────────────────────────────────
  [ROLES.FLEET_MANAGER]: [
    ACTIONS.VEHICLE_LIST, ACTIONS.VEHICLE_VIEW, ACTIONS.VEHICLE_EDIT, ACTIONS.VEHICLE_ADD,
    ACTIONS.VEHICLE_GROUP_LIST, ACTIONS.VEHICLE_GROUP_ADD, ACTIONS.VEHICLE_GROUP_DEL,
    ACTIONS.DRIVER_LIST, ACTIONS.DRIVER_EDIT, ACTIONS.DRIVER_ADD,
    ACTIONS.BOOKING_LIST, ACTIONS.BOOKING_EDIT,
    ACTIONS.TRACKING_LIVE, ACTIONS.TRACKING_HISTORY,
    ACTIONS.GEOFENCE_LIST, ACTIONS.GEOFENCE_ADD, ACTIONS.GEOFENCE_DEL, ACTIONS.GEOFENCE_EVENTS,
    ACTIONS.FUEL_LIST,
    ACTIONS.REPORTS_VIEW,
    ACTIONS.SETTINGS_ALL,
  ],

  [ROLES.OPERATIONS_MANAGER]: [
    ACTIONS.VEHICLE_LIST, ACTIONS.VEHICLE_VIEW,
    ACTIONS.VEHICLE_GROUP_LIST,
    ACTIONS.DRIVER_LIST,
    ACTIONS.BOOKING_LIST, ACTIONS.BOOKING_EDIT, ACTIONS.BOOKING_ADD,
    ACTIONS.TRACKING_LIVE, ACTIONS.TRACKING_HISTORY,
    ACTIONS.GEOFENCE_LIST, ACTIONS.GEOFENCE_EVENTS,
    ACTIONS.REPORTS_VIEW,
  ],

  [ROLES.BRANCH_MANAGER]: [
    ACTIONS.VEHICLE_LIST, ACTIONS.VEHICLE_VIEW,
    ACTIONS.DRIVER_LIST,
    ACTIONS.BOOKING_LIST, ACTIONS.BOOKING_EDIT, ACTIONS.BOOKING_ADD,
    ACTIONS.TRACKING_LIVE,
    ACTIONS.REPORTS_VIEW,
  ],

  // ────────────────────────────────────────────────
  // Financial & Compliance
  // ────────────────────────────────────────────────
  [ROLES.ACCOUNTANT]: [
    ACTIONS.FINANCE_LIST, ACTIONS.FINANCE_EDIT, ACTIONS.FINANCE_ADD,
    ACTIONS.FUEL_LIST, ACTIONS.FUEL_EDIT,
    ACTIONS.BOOKING_LIST,
    ACTIONS.REPORTS_VIEW,
  ],

  [ROLES.AUDITOR]: [
    ACTIONS.FINANCE_LIST,
    ACTIONS.FUEL_LIST,
    ACTIONS.VEHICLE_LIST,
    ACTIONS.BOOKING_LIST,
    ACTIONS.TRACKING_HISTORY,
    ACTIONS.REPORTS_VIEW,
  ],

  [ROLES.COMPLIANCE_OFFICER]: [
    ACTIONS.VEHICLE_LIST, ACTIONS.VEHICLE_VIEW,
    ACTIONS.DRIVER_LIST,
    ACTIONS.REMINDER_LIST,
    ACTIONS.REPORTS_VIEW,
  ],

  // ────────────────────────────────────────────────
  // Operational / Field roles
  // ────────────────────────────────────────────────
  [ROLES.DISPATCHER]: [
    ACTIONS.BOOKING_LIST, ACTIONS.BOOKING_EDIT, ACTIONS.BOOKING_ADD,
    ACTIONS.VEHICLE_LIST, ACTIONS.VEHICLE_VIEW,
    ACTIONS.DRIVER_LIST,
    ACTIONS.TRACKING_LIVE,
    ACTIONS.GEOFENCE_EVENTS,
  ],

  [ROLES.DRIVER]: [
    ACTIONS.VEHICLE_VIEW,
    ACTIONS.TRACKING_LIVE,
    ACTIONS.FUEL_ADD,
    ACTIONS.REMINDER_LIST,
  ],

  [ROLES.CONDUCTOR]: [
    ACTIONS.BOOKING_LIST,
    ACTIONS.BOOKING_ADD,
    ACTIONS.TRACKING_LIVE,
    ACTIONS.FINANCE_ADD,
  ],

  [ROLES.ROUTE_SUPERVISOR]: [
    ACTIONS.TRACKING_LIVE,
    ACTIONS.TRACKING_HISTORY,
    ACTIONS.GEOFENCE_EVENTS,
    ACTIONS.DRIVER_LIST,
    ACTIONS.VEHICLE_LIST,
  ],

  [ROLES.PLANNER]: [
    ACTIONS.VEHICLE_GROUP_LIST,
    ACTIONS.GEOFENCE_LIST, ACTIONS.GEOFENCE_ADD, ACTIONS.GEOFENCE_EDIT,
    ACTIONS.TRACKING_HISTORY,
    ACTIONS.REPORTS_VIEW,
  ],

  [ROLES.STAGE_OPERATOR]: [
    ACTIONS.VEHICLE_LIST,
    ACTIONS.BOOKING_LIST,
    ACTIONS.TRACKING_LIVE,
    ACTIONS.GEOFENCE_EVENTS,
  ],

  // ────────────────────────────────────────────────
  // Customer / External facing
  // ────────────────────────────────────────────────
  [ROLES.PASSENGER]: [
    ACTIONS.BOOKING_ADD,
    ACTIONS.BOOKING_LIST,
    ACTIONS.TRACKING_LIVE,
    ACTIONS.CUSTOMER_EDIT,
  ],

  [ROLES.CUSTOMER_SUPPORT]: [
    ACTIONS.BOOKING_LIST, ACTIONS.BOOKING_EDIT,
    ACTIONS.CUSTOMER_LIST, ACTIONS.CUSTOMER_VIEW, ACTIONS.CUSTOMER_EDIT,
    ACTIONS.TRACKING_LIVE,
    ACTIONS.REPORTS_VIEW,
  ],

  [ROLES.SALES_MANAGER]: [
    ACTIONS.CUSTOMER_LIST, ACTIONS.CUSTOMER_ADD, ACTIONS.CUSTOMER_EDIT,
    ACTIONS.BOOKING_LIST,
    ACTIONS.VEHICLE_LIST,
    ACTIONS.REPORTS_VIEW,
  ],

  // ────────────────────────────────────────────────
  // Vehicle / Asset owners & restricted
  // ────────────────────────────────────────────────
  [ROLES.VEHICLE_OWNER]: [
    ACTIONS.VEHICLE_VIEW,
    ACTIONS.TRACKING_LIVE,
    ACTIONS.TRACKING_HISTORY,
    ACTIONS.FINANCE_LIST,
    ACTIONS.FUEL_LIST,
    ACTIONS.REPORTS_VIEW,
  ],

  [ROLES.GUEST]: [
    ACTIONS.TRACKING_LIVE,              // very limited / public tracking
  ],

  // ────────────────────────────────────────────────
  // Regulatory / Oversight
  // ────────────────────────────────────────────────
  [ROLES.REGULATOR]: [
    ACTIONS.VEHICLE_LIST,
    ACTIONS.DRIVER_LIST,
    ACTIONS.TRACKING_HISTORY,
    ACTIONS.GEOFENCE_EVENTS,
    ACTIONS.REPORTS_VIEW,
  ],

  // Tenant / organization-level overview (if distinct from OWNER / COMPANY_OWNER)
  [ROLES.ORGANIZATION]: [
    ACTIONS.VEHICLE_LIST,
    ACTIONS.FINANCE_LIST,
    ACTIONS.CUSTOMER_LIST,
    ACTIONS.REPORTS_VIEW,
  ],
};