<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 japanese_bus_osaka_city_bus_osaka.glb --transform
Author: VRC-IW (https://sketchfab.com/VRC-IW)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/japanese-bus-osaka-city-bus-osaka-c42e1d509f714ce2ae0ec55b51fa8faf
Title: Japanese bus "Osaka City Bus" (Osaka)
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/japanese_bus_osaka_city_bus_osaka-transformed.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cube003_OsakaCity_0.geometry}
      material={gltf.materials.OsakaCity}
      position={[0, 89.69, 4921.14]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
